### ISSUE TITLE
Consider adding default visualizers for Quaternion data

### ISSUE THREAD

**Issue by ChucklesOnGitHub** [open-ephys/onix-bonsai-onix1#136]
![image](https://github.com/user-attachments/assets/e2273fb1-45f1-4b7d-b95c-3037a14398a9)

**Comment by bparks13** [comment]
As far as I am aware, there is no direct visualizer for a Quaternion, or any of the other types with multiple axes (e.g., Acceleration, Gravity, etc.). What we can do is use a `RollingGraph` visualizer (found in the `Bonsai.Design.Visualizers` package) and connect it to the Quaternion output (see below).

![image](https://github.com/user-attachments/assets/f832e5a6-526e-4df6-bced-5b61460390c6)

The `RollingGraph` can then be visualized by selecting the **Bonsai.Design.Visualizers.RollingGraphVisualizer** option in **Show Visualizer**.

**Comment by jonnew** [comment]
This was my main hesitation when moving away from just using Mats, which we were doing before. Its definitely correct to use these nice types but the lack of easy visualization is a big hit for users.

**Comment by ChucklesOnGitHub** [comment]
Thanks. I had forgotten that difference between the old and the new library. This is actually already [addressed in the docs](https://cjsha.github.io/onix-bonsai-docs/articles/getting_started-visualizing_data.html). I've added the RollingGraph nodes to the example workflows. (You can follow work on example workflows here: https://github.com/cjsha/onix-bonsai-docs/issues/1).

**Comment by jonnew** [comment]
@glopesdev Is there a way that we can give the rolling graph as default visualizer for Quaternion and Point data?

**Comment by glopesdev** [comment]
@jonnew yes, but since this has to be done in the Design package, I would recommend doing this for the 0.2.0 package.

**Comment by jonnew** [comment]
@glopesdev can you provide an example of how this has been done in another package? We might be able to take it from there.

**Comment by glopesdev** [comment]
The quickest would be to reuse `TimeSeriesVisualizer` directly similar to [`ScalarVisualizer`](https://github.com/bonsai-rx/bonsai/blob/main/Bonsai.Vision.Design/ScalarVisualizer.cs).

Alternatively for more fine-grained customization you can make your own series plot similar to [`ScalarHistogramVisualizer`](https://github.com/bonsai-rx/bonsai/blob/main/Bonsai.Vision.Design/ScalarHistogramVisualizer.cs).

**Comment by jonnew** [comment]
Thanks @glopesdev this worked great.
