### ISSUE TITLE
ConfigureNeuropixelsV1e node error messages improvements

### ISSUE THREAD

**Issue by ChucklesOnGitHub** [open-ephys/onix-bonsai-onix1#138]
![image](https://github.com/user-attachments/assets/41e51ad1-229e-4019-bc63-e517d9a9cf08)
Empty filename path error should be “Gain calibration file must be specified.” or “Adc calibration file must be specified.” to match NPV2e.

![image](https://github.com/user-attachments/assets/d14b698a-1e33-4796-88a8-95476cc482d4)
Wrong calibration file popup does not report probe serial number. Should say “Probe serial number xxx does not match xx calibration file serial number xxx.” to match NPV2e and help the user identify the mistake.

![image](https://github.com/user-attachments/assets/bbfdf009-ec0d-445d-b4c3-7e1a6dbe6407)
Cryptic error message when no DeviceName specified in NeuropixelsV1eData node. Suggestion: “DeviceName must be specified”.

**Comment by jonnew** [comment]
This has been addressed for 2.0 code, but we still need to fix for 1.0. See this for an example:

https://github.com/open-ephys/onix-bonsai-onix1/blob/7ac700fb8a696d4d9f8d97c9d1b85765b9951ca6/OpenEphys.Onix1/NeuropixelsV2.cs#L120
