### ISSUE TITLE
Consider specifying a list of drivers that users choose from a drop-down

### ISSUE THREAD

**Issue by bparks13** [open-ephys/onix-bonsai-onix1#178]
In the `ContextTask`, currently users must type in the driver they wish to use (see [here](https://github.com/neurogears/onix-refactor/blob/4088fd6687c775fdf8534e8aa7de7cb659fbef44/OpenEphys.Onix/OpenEphys.Onix/ContextTask.cs#L55)). To minimize the possibility of mistyping a driver name, it is possible to use [TypeConverter.GetStandardValues](https://learn.microsoft.com/en-us/dotnet/api/system.componentmodel.typeconverter.getstandardvalues?view=net-8.0) to define a list of strings that are valid driver names.

To further minimize the possibility of error, overriding the `GetStandardValuesExclusive` method can disable the ability to type in the field, meaning that users are confined to the given list of drivers.

**Comment by jonnew** [comment]
In conversation with @aacuevas he let us know that currently, `ContextTask` is not fully abstracted away from RIFFA. For this reason, it might be advisable not to expose the driver property at all.
