### ISSUE TITLE
BreakoutDigitalPortState Nomenclature Overlap

### ISSUE THREAD

**Issue by cjsha** [open-ephys/onix-bonsai-onix1#188]
``BreakoutDigitalPortState`` is both:
- [parameter in BreakoutDigitalOutput.cs](https://github.com/open-ephys/onix-bonsai-onix1/blob/e7a63cb7deb1fe08a056746ae4742fd500026f64/OpenEphys.Onix1/BreakoutDigitalOutput.cs#L13)
-  [enum in ConfigureBreakoutDigitalIO.cs](https://github.com/open-ephys/onix-bonsai-onix1/blob/e7a63cb7deb1fe08a056746ae4742fd500026f64/OpenEphys.Onix1/ConfigureBreakoutDigitalIO.cs#L75)

This doesn't seem to affect the behavior of the software which is why I call it an overlap instead of conflict - it's not severe. This does create a corner case when generating documentation, however, which is how I noticed this. I'm sure I can overcome this on the docs side, but I still wanted to mention it here in case it does matter to us.

**Comment by glopesdev** [comment]
@cjsha I'm not sure I understand the issue. There doesn't seem to be an overlap here in the sense that the operator `BreakoutDigitalOutput` is a sink that returns values of type `BreakoutDigitalPortState`, which is exactly what is intended.

How exactly is this creating an issue with DocFX?

**Comment by cjsha** [comment]
Sorry, this issue came from my naivete about enums in C#. This is not a real issue.

There also wasn't any issue with DocFx. There was an issue with my template. I had to add more logic to my template to accommodate for operators that subscribe to an observable sequence of enums. 

Sorry about this!
