### ISSUE TITLE
ProbeConfigurationA & ProbeConfigurationB properties lack documentation

### ISSUE THREAD

**Issue by cjsha** [open-ephys/onix-bonsai-onix1#202]
I assume that documentation for these NeuropixelsV2eBeta and NeuropixelsV2e properties  are postpone until the configuration GUIs are available for the 0.2.0 release. Either way, I want to note that info is missing in the interim, at least as a reminder.

![image](https://github.com/user-attachments/assets/df8aa22f-1a3d-43a7-9f21-878878209de2)

If the probe configuration GUI is sufficiently intuitive, it might suffice to put some instructions on how to use the GUIs in the remarks which get populated here in this table? Not sure how much instruction will be necessary here.

**Comment by cjsha** [comment]
The locations of the potential \<remarks\> comments to would be here:
https://github.com/open-ephys/onix-bonsai-onix1/blob/7ac700fb8a696d4d9f8d97c9d1b85765b9951ca6/OpenEphys.Onix1/ConfigureNeuropixelsV2eBeta.cs#L43-L48
https://github.com/open-ephys/onix-bonsai-onix1/blob/7ac700fb8a696d4d9f8d97c9d1b85765b9951ca6/OpenEphys.Onix1/ConfigureNeuropixelsV2eBeta.cs#L62-L67

**Comment by cjsha** [comment]
and also here:
https://github.com/open-ephys/onix-bonsai-onix1/blob/7ac700fb8a696d4d9f8d97c9d1b85765b9951ca6/OpenEphys.Onix1/ConfigureNeuropixelsV2e.cs#L33-L38
https://github.com/open-ephys/onix-bonsai-onix1/blob/7ac700fb8a696d4d9f8d97c9d1b85765b9951ca6/OpenEphys.Onix1/ConfigureNeuropixelsV2e.cs#L52-L57

**Comment by jonnew** [comment]
I think that all we have to do here is to add a <remark> section that states a sentence or two about how these properties are generally configured via a GUI.

**Comment by bparks13** [comment]
`NeuropixelsV2e` probe configuration variables are updated in #214.

When GUIs are added for `NeuropixelsV2eBeta`, the probe configuration variables will be updated accordingly.

**Comment by bparks13** [comment]
Moving this to 0.3 since we are not going to release `NeuropixelsV2eBeta` GUIs until then.
