### ISSUE TITLE
Ensure that all node Properties are categorized

### ISSUE THREAD

**Issue by jonnew** [open-ephys/onix-bonsai-onix1#206]
All properties that are exposed as parameters of Bonsai operators need to be be tagged with the appropriate `Configuration` or `Acquisition` Attribute. For example this should be `Acquisition`:

https://github.com/open-ephys/onix-bonsai-onix1/blob/7ac700fb8a696d4d9f8d97c9d1b85765b9951ca6/OpenEphys.Onix1/Headstage64ElectricalStimulatorTrigger.cs#L49

**Comment by bparks13** [comment]
`NeuropixelsV2e` and `NeuropixelsV2eBeta` categories are updated in #214.
