### ISSUE TITLE
Description connecting <xyz>Data operators and configure<xyzHeadstage> operators

### ISSUE THREAD

**Issue by cjsha** [open-ephys/onix-bonsai-onix1#207]
![Screenshot 2024-08-08 124501](https://github.com/user-attachments/assets/94d52a65-561f-4a6c-bb52-0649aa194c72)

The part underlined by red is repeated throughout the docs (besides [BreakoutDigitalInput](https://open-ephys.github.io/onix1-bonsai-docs/api/OpenEphys.Onix1.BreakoutDigitalInput.html), also [Bno055Data](https://open-ephys.github.io/onix1-bonsai-docs/api/OpenEphys.Onix1.Bno055Data.html) for example). What does it mean to be "linked"? I'm not sure a naive user would know. I would replace it with a more concrete description such as:

> The BreakoutDigitalInput ``DeviceName`` property must correspond to the ``DeviceName`` property of a ``ConfigureBreakoutBoard`` operator to produce data.

or something like that

The corresponding code for this specific example is:

https://github.com/open-ephys/onix-bonsai-onix1/blob/7ac700fb8a696d4d9f8d97c9d1b85765b9951ca6/OpenEphys.Onix1/BreakoutDigitalInput.cs#L12-L15

**Comment by jonnew** [comment]
Related to #229

**Comment by jonnew** [comment]
There are two issues that need to be addressed here

1. The complete process of setting up a configuration chain and then setting up 'receiver' operators to capture data from the devices defined in the configuration needs to be described in high level terms in the getting started guide. There should be 2 major pages to do this: Configuration and Acquisition. The first focuses on describing and defining configuration chain. The second focuses on linking Data operators to this chain, running the workflow, and visualizing data.
2. The XML description should not just say "link" but should reference and describe the `DeviceName` property that performs the "linking" ( e.g. linked by selecting the corresponding `DeviceName` property value).
