### ISSUE TITLE
Headstage64 ElectricalStimulator & OpticalStimulator Remarks require more information

### ISSUE THREAD

**Issue by cjsha** [open-ephys/onix-bonsai-onix1#211]
There should be more instructions on how to use the ``ElectricalStimulator`` and ``OpticalStimulator`` properties on the ConfigureHeadstage64. I think it would be proper to include more info in their remarks? in addition to other pages in the docs.

![image](https://github.com/user-attachments/assets/56903d64-cd5f-4743-b1cd-71d6eaf6b6c7)

Also, I know these properties don't necessarily belong in the Misc subheader, this is its own [issue that belongs to the docs repo](https://github.com/open-ephys/onix1-bonsai-docs/issues/11).

**Comment by jonnew** [comment]
I think this might be handled by #288 because now these Configuration operatators will have a link the the trigger operators in their remarks, which provide more information on use. Beyond that, I think its best left to the headstage-64 user guide article, unless I'm not understanding something.

The misc classification issue was fixed in #226.

If you disagree, keep this open and let me know. Otherwise, I'm voting to close.

**Comment by cjsha** [comment]
I actually don't see where these have links to the trigger operators in their remarks. They don't have remarks at all in that issue-207 branch which is the one being merged in #288

https://github.com/open-ephys/onix-bonsai-onix1/blob/e020b3313bc3825954eac22c00dec716ce1d6f40/OpenEphys.Onix1/ConfigureHeadstage64.cs#L81-L87
https://github.com/open-ephys/onix-bonsai-onix1/blob/e020b3313bc3825954eac22c00dec716ce1d6f40/OpenEphys.Onix1/ConfigureHeadstage64.cs#L89-L95

but in any case, the original post for this issue is old. This is how this page looks now: 
https://open-ephys.github.io/onix1-bonsai-docs/api/OpenEphys.Onix1.ConfigureHeadstage64.html
![image](https://github.com/user-attachments/assets/bab8d23d-4e1f-4fab-ab5c-97ef0f7d3d37)

That's generic text that the website serves when a device doesn't have public properties. I think it's insufficient - people won't know that they need to connect a trigger operator to get the stimulator functionality going. If you write remarks where I github perma-linked above, I can probably put those remarks there.

**Comment by bparks13** [comment]
@cjsha it looks like the comments linking the configure node to the trigger operator exist in the device nodes. Would it be sufficient to use `<inheritdoc>` from the configure device node in the configure headstage node? I remember seeing something about a hierarchical inheritance, so we can keep the summary written in the headstage node, but pull in the remarks to then display the correct information here.

**Comment by jonnew** [comment]
Im going to re-assign this one to @bparks13 to explore these ideas.
