### ISSUE TITLE
Headstage64ElectricalStimulatorTrigger not propagating trigger information

### ISSUE THREAD

**Issue by bparks13** [open-ephys/onix-bonsai-onix1#83]
While working on #78, we had to refactor the `Rhs2116StimulusTrigger` to correctly propagate information using both BehaviorSubjects and Observers. This refactor was based on `Headstage64ElectricalStimulatorTrigger`. 

During this refactor, we noticed that the observer in `Headstage64ElectricalStimulatorTrigger` does not correctly implement `OnNext()` in that it does not continue to propagate the incoming boolean value.

That is to say, the `Headstage64ElectricalStimulatorTrigger` is implemented as below:

```c#
var triggerObserver = Observer.Create<bool>(
    value => device.WriteRegister(Headstage64ElectricalStimulator.TRIGGER, value ? 1u : 0u),
    observer.OnError,
    observer.OnCompleted);
```

Meanwhile, the `Rhs2116StimulusTrigger` is now implemented as below:
```c#
var triggerObserver = Observer.Create<bool>(
    value =>
    {
        device.WriteRegister(Rhs2116Trigger.TRIGGER, value ? 1u : 0u);
        observer.OnNext(value);
    },
    observer.OnError,
    observer.OnCompleted);
```

The fix is simple; update `Headstage64ElectricalStimulatorTrigger` to propagate the incoming value.

**Comment by jonnew** [comment]
And make sure this fix is applied to other sinks that may have the same issue (e.g. Optical stimulator)
